- hosts: localhost
  roles:
    - provision-instance

- hosts: new_instances
  connection: ssh
  remote_user: tjohnson
  gather_facts: no
  become: true
  tags:
    - deploy

  roles:
    - deploy-service
