---
- name: Destroy an instance
  gcp_compute_instance:
    name: test
    machine_type: n1-standard-1
    zone: us-central1-a
    project: "{{ gcp_project }}"
    state: absent
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"


- name: Destroy firewall
  gcp_compute_firewall:
    name: my-firewall
    allowed:
      - ip_protocol: tcp
        ports: ['80', '22', '443', '8080']
    target_tags: my-instance
    source_ranges: ['0.0.0.0/0']
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent
  register: firewall

- name: delete a network
  gcp_compute_network:
    name: my-network
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent
  register: network

- name: delete a address
  gcp_compute_address:
    name: my-address
    region: us-central1
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent
  register: address

